name: Generate Index Files

on:
  push:
    branches:
      - main
    paths:
      - 'DATA/**'
      - '.github/workflows/generate-index.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'DATA/**'
      - '.github/workflows/generate-index.yml'
  workflow_dispatch:
  repository_dispatch:
    types: [update_index]

permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整的 git 历史
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install xml2js
          
      - name: Generate index files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const xml2js = require('xml2js');
          
          async function parseXML(xmlPath) {
            try {
              const xmlContent = fs.readFileSync(xmlPath, 'utf8');
              const parser = new xml2js.Parser();
              const result = await parser.parseStringPromise(xmlContent);
              return result.resource;
            } catch (error) {
              console.error(\`Error parsing XML file \${xmlPath}:\`, error);
              return null;
            }
          }
          
          async function generateIndex(baseDir) {
            if (!fs.existsSync(baseDir)) {
              console.log(\`Directory \${baseDir} does not exist\`);
              return;
            }
            
            try {
              // 获取所有子目录
              const subDirs = fs.readdirSync(baseDir)
                .filter(file => fs.statSync(path.join(baseDir, file)).isDirectory());
              
              console.log(\`Found \${subDirs.length} directories in \${baseDir}\`);
              
              const items = await Promise.all(
                subDirs.map(async dirName => {
                  const fullDirPath = path.join(baseDir, dirName);
                  const xmlPath = path.join(fullDirPath, 'info.xml');
                  
                  // 检查目录是否完整
                  if (!fs.existsSync(xmlPath)) {
                    console.log(\`Skipping incomplete directory: \${fullDirPath}\`);
                    return null;
                  }
                  
                  const xmlData = await parseXML(xmlPath);
                  if (!xmlData) {
                    console.log(\`Skipping directory with invalid XML: \${fullDirPath}\`);
                    return null;
                  }
                  
                  // 打印 XML 数据以便调试
                  console.log(\`XML data for \${dirName}:\`, JSON.stringify(xmlData, null, 2));
                  
                  // 创建基础 item 对象
                  const item = {
                    name: xmlData.name?.[0] || dirName,
                    path: fullDirPath.replace(/\\\\/g, '/'),
                    author: xmlData.author?.[0] || '',
                    description: xmlData.description?.[0] || '',
                    gameVersion: xmlData.gameVersion?.[0] || ''
                  };
                  
                  // 添加预览图信息
                  const imageFile = xmlData.imageFile?.[0];
                  if (imageFile) {
                    const imagePath = path.join(fullDirPath, imageFile);
                    if (fs.existsSync(imagePath)) {
                      item.imageSize = fs.statSync(imagePath).size;
                    }
                  }
                  
                  // 添加资源文件信息
                  const resourceFile = xmlData.resourceFile?.[0];
                  if (resourceFile) {
                    const resourcePath = path.join(fullDirPath, resourceFile);
                    if (fs.existsSync(resourcePath)) {
                      item.resourceSize = fs.statSync(resourcePath).size;
                    }
                  }
                  
                  // 根据目录类型添加特定字段
                  if (baseDir.includes('/mods/')) {
                    // 添加模组特有字段
                    if (xmlData.type) {
                      item.type = xmlData.type[0];
                    }
                    if (xmlData.isModify) {
                      item.isModify = xmlData.isModify[0];
                    }
                  } else if (baseDir.includes('/maps/')) {
                    // 添加地图特有字段
                    if (xmlData.size) {
                      item.size = xmlData.size[0];
                    }
                  }
                  
                  // 打印生成的 item 以便调试
                  console.log(\`Generated item for \${dirName}:\`, JSON.stringify(item, null, 2));
                  
                  return item;
                })
              );
              
              // 过滤掉无效的项
              const validItems = items.filter(item => item !== null);
              
              const indexPath = path.join(baseDir, 'index.json');
              fs.writeFileSync(indexPath, JSON.stringify(validItems, null, 2));
              console.log(\`Generated \${indexPath} with \${validItems.length} items\`);
              
              // 输出变更日志
              console.log('Changes in index:');
              validItems.forEach(item => {
                console.log(\`- \${item.name} (Path: \${item.path})\`);
              });
            } catch (error) {
              console.error(\`Error processing \${baseDir}:\`, error);
            }
          }
          
          // 生成索引文件
          Promise.all([
            generateIndex('DATA/mods'),
            generateIndex('DATA/maps')
          ]).then(() => {
            console.log('Index generation completed');
          }).catch(error => {
            console.error('Error during index generation:', error);
            process.exit(1);
          });
          "
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 检查文件是否存在并添加
          if [ -f "DATA/mods/index.json" ]; then
            git add DATA/mods/index.json
          fi
          
          if [ -f "DATA/maps/index.json" ]; then
            git add DATA/maps/index.json
          fi
          
          # 只有在有更改时才提交和推送
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update index files with XML data"
            git push
            
            # 清除 jsDelivr 缓存
            echo "清除 jsDelivr 缓存..."
            curl -X POST "https://purge.jsdelivr.net/gh/MORAN-hub-code/MORAN-hub-code.github.io@main/DATA/mods/index.json"
            curl -X POST "https://purge.jsdelivr.net/gh/MORAN-hub-code/MORAN-hub-code.github.io@main/DATA/maps/index.json"
          fi 